### PR TITLE
2nd Long - Run Results 

### PR DESCRIPTION
**Pull request by mayaafields**
The model just finished running for 1000 days and I looked at the contour plot results and they look completely different than the first run. I'm not sure what I did wrong.
contour_plot_KE_01
contour_plot_qNH3a2_deep_01
contour_plot_qH2Oa2_deep_01
contour_plot_tempa_deep_01

### CODE REVIEW

**Comment by mayaafields** [comment]
Using the original model run, I have started looking into the advection equation for H2O and NH3.
dwqH2Odt_mvavg_compare_anomaly
dwqNH3dt_mvavg_compare_anomaly

**Comment by mayaafields** [comment]
dwqNH3dt_mvavg_compare
dwqH2Odt_mvavg_compare

**Comment by luminoctum** [comment]
It seems to me that some profiles are matching but I don't understand the terms by looking at the graphs here. Can you start writing a document on the setting of your experiments, the definition of the terms? Set up the document on overleaf and share that with me. Write it as a journal article but save the effort for the introduction. Save this case and keep running the model while you are writing the document. Set up a dry case in which there is no water and ammonia. Set up a second case for water only and set up a third case for ammonia only. Do not delete any result even though you are not sure if it is correct or result. Every result is valuable. Save the executable file, the input file and pgen file so that you can rerun or continue running your previous models.

Also, if you edited a file and would like to merge it to the main branch, use `pull request`. If you need comments on the result/plot but do not wish to merge changes or codes, open up an `issue`. Set up a Github `project` to track the issues you open. They will automatically appear in the right column under `project`.  You can also try a tool called [obsidian](https://obsidian.md/).

**Comment by mayaafields** [comment]
I will work on the document and share it with you. When I change the model to a dry atmosphere or a moist atmosphere with only one of the condensable species are there specific inputs I need to change? 

In the configure, I assumed I would change the --nvapor paramater from 2 to 0 for a dry atmosphere and from 2 to 1 for only H2O or NH3. If I change that parameter does it know to ignore the qvapor1 and qvapor2 in the problem or do I have to comment them out? Does the chemistry have to be altered at all for the different cases?

**Comment by luminoctum** [comment]
> In the configure, I assumed I would change the --nvapor paramater from 2 to 0 for a dry atmosphere and from 2 to 1 for only H2O or NH3. If I change that parameter does it know to ignore the qvapor1 and qvapor2 in the problem or do I have to comment them out? Does the chemistry have to be altered at all for the different cases?

Actually, you don't need to do anything else other than setting either `qvapor1` or `qvapor2` to zero. It will be less efficient than reconfigure the program to `nvapor = 1`. But it is more convenient. So, just change the value of `qvapor1` or `qvapor2` will do the job.

**Pull request closed without merging**
